### PR TITLE
fix: handle case of missing `.cmj` when trying to inline external field

### LINKED ISSUE #658: Cannot use virtual modules without specify implementation library in libraries
dune version: 3.9.1
ocaml version: 4.14.1
melange version: both 1.0.0 58f3bcfc7dca5eea708de8e50e9a5e0ceda66b3c reproduced

A miminal reproducible demo is uploaded here: 

https://github.com/hackwaly/minimal-melange-virtual-library

```
➜  minimal-melange-virtual-library git:(master) dune build @melange
File "app/app.ml", line 1:            
Error: Compiler_specific not found, it means either the module does not exist or it is a namespace
```

Howerver this version works
https://github.com/hackwaly/minimal-melange-virtual-library/commit/a9ea6c641391d382ae770863a388bcb90238540a

### PR DESCRIPTION
**Pull request by anmonteiro**
this is the melange part of the fix for #658. 

- Melange looks for some inlining information in the `.cmj` files for implementations. When compiling virtual libraries, `.cmj` files are deferred until a specific implementation has been selected, so they won't be available at this time
- There's a more thorough explanation in the code about what the fix does.

fixes #658 

TODO:

- [x] add a blackbox-test

### CODE REVIEW

File: jscomp/core/lam_compile.ml [hunk 1]
```diff
@@ -187,12 +187,24 @@ type initialization = J.block
...
+          a dune virtual library where one of the modules uses a binding from
+          any of its virtual modules. Because we're programming against the
+          interface file at this point, we can emit the fallback expression
+          too.
+  *)
   match Lam_compile_env.query_external_id_info id name with
   | { persistent_closed_lambda = Some lam; _ } when Lam_util.not_function lam ->
       compile_lambda lamba_cxt lam
-  | _ ->
+  | _ | (exception Mel_exception.Error (Cmj_not_found _)) ->
```
Comment (jchavarri) [inline jscomp/core/lam_compile.ml:207]: Probably out of scope, but I wonder if it'd make sense to have `load_unit` return a result type or some other variant, rather than raise exceptions? 

I can see other usages of that function and `query_external_id_info` that don't process `Cmj_not_found`, and after the changes to support virtual libraries, that's not an unexpected situation anymore.

Comment (anmonteiro) [reply jscomp/core/lam_compile.ml:207]: I feel like we want it to fail when a `.cmj` isn't found, except for this one time where we know it could not be there.

In principle, all the other usages should have a `.cmj` file present that we can lean on.

Comment (anmonteiro) [reply jscomp/core/lam_compile.ml:207]: Oh you might actually be right. I think I missed a few usages
